[package]
name = "ya-sgx"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-client-model = "0.1"
ya-core-model = { version = "0.1", features = ["sgx"] }
ya-service-bus = "0.2"
graphene_api = { git = "https://github.com/golemfactory/graphene-rust.git", rev = "8e14e8f012e790ccce5c696f20c1d750ca3f4398" }

anyhow = "1.0"
