[package]
name = "ya-sgx"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
graphene = { version = "0.3", git = "https://github.com/golemfactory/graphene-rust.git", features = [ "ias" ] }
ya-client-model = "0.1"
ya-core-model = { version = "0.1", features = ["sgx"] }
ya-service-bus = "0.2"
