[package]
name = "market-api"
version = "0.0.0"

[dependencies]
uuid = { version = "0.7", features = ["v4"] }
nom = "2.0"
asnom = { git = "https://github.com/dequbed/asnom.git" }
chrono = "0.4"
regex = "1"
semver = "0.9.0"
decimal = "2.0"


