[workspace]
members = [
    "agent/provider",
    "agent/requestor",
    "core/activity",
    "core/identity",
    "core/market",
    "core/model",
    "core/net",
    "core/payment",
    "core/persistence",
    "core/serv",
    "core/serv-api",
    "exe-unit/api",
    "exe-unit/dummy",
    "exe-unit/wasm-mozjs",
    "exe-unit/wasmtime",
    "interfaces/client",
    "interfaces/model",
    "service-bus/bus",
    "service-bus/derive",
    "service-bus/proto",
    "service-bus/router",
    "service-bus/util",
]

[patch.crates-io]
ya-core-model = { path = "core/model" }
ya-exe-api = { path = "exe-unit/api" }
ya-identity = { path = "core/identity" }
ya-model = { path = "interfaces/model" }
ya-sb-proto = { path = "service-bus/proto" }
ya-sb-util = { path = "service-bus/util" }
ya-service-api = { path = "core/serv-api"}
ya-service-bus = { path = "service-bus/bus/" }
