[package]
name = "yagna"
version = "0.1.1"
description = "Yagna server daemon and CLI"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-service-api = { path = "../serv-api"}
ya-identity = { path = "../identity" }

actix-web = "1.0"
anyhow = "1.0"
appdirs="0.2"
flexi_logger = "0.14"
log = "0.4"
structopt = "0.3"
