[package]
name = "ya-core-model"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = ['with-diesel']
full = ['activity', 'appkey', 'identity']
activity = []
identity = []
appkey = []
with-diesel=['diesel']

[dependencies]
ya-model = "0.1"
ya-service-bus = "0.1"

chrono = { version = "0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
diesel = { version = "1.4", optional = true, features=["sqlite"] }
thiserror = "1.0.9"