[package]
name = "ya-service-api"
version = "0.1.0"
description = "Yagna server daemon and CLI interface for modules"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
prettytable-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
futures={ version= "0.3", features=['compat']}
actix="0.8"