[package]
name = "ya-runtime-api"
description = "Communication API between the Runtime and ExeUnit Supervisor. Provides server implementation for Runtime and client implementation for Supervisor."
version = "0.4.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://github.com/golemfactory/yagna/tree/master/exe-unit/runtime-api"
repository = "https://github.com/golemfactory/yagna"

[[example]]
name = "runtime-server-mock"
required-features = ["server"]

[features]
default = ['server']
codec = []
server = [
    'prost' ,
    'futures',
    'tokio',
    'tokio-util'
]

[dependencies]
anyhow = "1.0.31"
bytes = "1.1.0"
futures = { version = "0.3", optional = true  }
log = "0.4.8"
prost = { version = "0.9.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.17.0" , optional = true, features=["io-std", "rt", "rt", "process", "sync"] }
tokio-util = { version = "0.7.0", optional = true, features = ["codec"] }

[build-dependencies]
prost-build = "0.9.0"

[dev-dependencies]
tokio = { version = "1.17.0" , features=["io-std", "macros", "rt", "time"] }
env_logger = "0.7"
