[package]
name = "ya-persistence"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
build = "build.rs"


[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4", features = ["sqlite", "r2d2", "chrono"] }
dotenv = "0.14"
r2d2 = "0.8"


[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"