[package]
name = "ya-persistence"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4", features = ["sqlite", "r2d2", "chrono"] }
chrono = { version = "0.4.6", features = ["serde"] }
r2d2 = "0.8"
dotenv = "0.14"


[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"