[package]
name = "ya-market-resolver"
version = "0.2.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
nom = "2.0"
asnom = { git = "https://github.com/dequbed/asnom.git" }
chrono = "0.4"
log = "0.4.8"
regex = "1"
semver = "0.9.0"
decimal = "2.0"


