[package]
name = "golem"
description = "User friedly CLI for running provider"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-compile-time-utils = "0.1"
actix-rt = "1.0"
anyhow = "1.0"
bigdecimal = "0.1.0"
byte-unit = "4.0"
chrono = "0.4"
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strip-ansi-escapes = "0.1"
structopt = "0.3"
tokio = { version = "0.2", features = ["process", "rt-core", "signal", "time", "io-util"] }
url = "2.1"
directories = "2.0.2"
promptly = "0.3.0"
names = "0.10.0"
