[package]
name = "ya-version"
version = "0.0.1"
description = "Version handling"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-persistence = "0.2"

anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["chrono", "sqlite", "r2d2"] }
diesel_migrations = "1.4"
log = "0.4"
self_update = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["time", "sync"] }
