[package]
name = "ya-agreement-utils"
version = "0.2.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
homepage = "https://github.com/golemfactory/yagna"
repository = "https://github.com/golemfactory/yagna"
license = "LGPL-3.0"
description="Yagna agreement utils"
keywords=["golem", "yagna"]

[dependencies]
ya-client-model = { git = "https://github.com/golemfactory/ya-client.git", rev = "9b17a8de0c4709bfa7827d4c372e9db729e81c61" }

serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.11"
thiserror = "1.0.10"

[dev-dependencies]
anyhow = "1.0.31"
tempdir = "0.3.7"
