[package]
name = "ya-identity"
version = "0.1.0"
description = "Yagna identity management"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-core-model = { version = "0.1", features = ["identity"], default-features = false }
ya-service-api = "0.1"
ya-service-bus = "0.1"

anyhow = "1.0"
ethkey = "0.3"
futures = "0.3"
log = "0.4"
serde_json = "1.0"
structopt = "0.3"

