[package]
name = "ya-identity"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-service-api = { path = "../serv-api"}

anyhow = "1.0"
ethkey = "0.3"
serde_json = "1.0"
structopt = "0.3"
