[package]
name = "ya-utils-networking"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = ["dns"]
dns = ["anyhow",  "url", "trust-dns-resolver/mdns"]
vpn = ["ya-relay-stack", "ipnet", "thiserror"]

[dependencies]
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
regex = "1"

anyhow = { version = "1.0", optional = true }
trust-dns-resolver = { version = "0.19", optional = true }
url = { version = "2.2", optional = true }

ya-relay-stack = { git = "https://github.com/golemfactory/ya-relay.git", branch = "mf/outbound-inet", optional = true }
ipnet = { version = "2.3", optional = true }
thiserror = { version = "1.0", optional = true }
