[package]
name = "ya-api-macros"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies.quote]
version = "1.0.3"

[dependencies.syn]
version = "^1"
features = ["full"]
