[package]
name = "ya-activity"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-core-model = "0.1"
ya-model = "0.1"
ya-service-bus = "0.1"

actix-web = "1.0"
anyhow = "1.0"
chrono = "0.4"
diesel = { version = "^1.1.0", features = ["chrono", "sqlite", "r2d2"] }
futures = { version = "0.3", features = ["compat"] }
r2d2 = "0.8"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
shlex = "0.1"
thiserror = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

