[package]
name = "tokio-process-ns"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc= "0.2"
nix="0.11.0"
tokio= { version = "0.2", features=["process"] }

[dev-dependencies]
tokio= { version = "0.2", features=["process", "rt-threaded", "macros"] }
