[package]
name = "ya-client"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-model = { path = "../model" }

async-trait = "0.1"
awc = "1.0.0-alpha.3"
failure = "0.1.6"
futures = { version = "0.3", features = ["compat"] }
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
actix-rt = "1.0.0-alpha.3"
