name: Build .deb

on:
  push:
    branches:
      - master
      - km/deb-integration-tests
    tags:
      - v*

jobs:

  build:
    name: Build (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "::set-env name=CONTAINER_OUTPUT_PATH::/src/target/debian"
          echo "::set-env name=JOB_OUTPUT_PATH::${{ runner.temp }}/deb_packages"
      - name: Build Docker image
        run: docker build . -f build-deb.Dockerfile -t build-deb

      - name: Build yagna.deb file
        run: docker run --env PACKAGE_NAME=yagna -v $JOB_OUTPUT_PATH:$CONTAINER_OUTPUT_PATH build-deb 

      - name: Commit built image
        run: docker commit $(docker ps -aq --filter "ancestor=build-deb") build-deb

      - name: Build ya-sb-router.deb file
        run: docker run --env PACKAGE_NAME=ya-sb-router -v $JOB_OUTPUT_PATH:$CONTAINER_OUTPUT_PATH build-deb

      - name: Upload .deb packages
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ${{ env.JOB_OUTPUT_PATH }}

  yagna-e2e:
    name: Run integration tests (yagna E2E)
    runs-on: ubuntu-latest
    needs: build    # TODO: Update name?
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'golemfactory/yagna-integration'
          token: ${{ secrets.YAGNA_WORKFLOW_TOKEN }}

      - name: Configure python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.YAGNA_WORKFLOW_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Run test suite
        env:
          GITHUB_API_TOKEN: ${{ secrets.YAGNA_WORKFLOW_TOKEN }}
        run: python -m pytest test/yagna/e2e -svx --log-cli-level=DEBUG

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: goth-logs
          path: /tmp/yagna-tests

