name: Create .deb

on:
  push:
    branches:
      - master
      - filip/install-deb

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f create-deb.Dockerfile -t create-deb
    - name: Copy .deb file
      run: docker run create-deb bash -c "cat /src/target/debian/*.deb" >yagna.deb
    - name: Download artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yagna.deb
        path: yagna.deb
