name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f create-deb.Dockerfile -t create-deb
    - name: Copy .deb file
      run: docker run create-deb cat /src/target/debian/*.deb >yagna.deb
