name: Release
on:
  push:
    tags:
      - v*
      - pre-rel-*

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let tag = context.payload.ref.replace(/.*\//, '');
            try {
              let release =  await github.request("GET /repos/:owner/:repo/releases/tags/:tag", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
            }
            catch(e) {
              let release =  await github.request("POST /repos/:owner/:repo/releases", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                data: {
                  tag_name: tag,
                  prerelease: true
                }
              });
              console.log(release.data.upload_url);
            }
  build:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos

    env:
      X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: c:/vcpkg/installed/x64-windows-static
      MACOSX_DEPLOYMENT_TARGET: 10.13
      OPENSSL_STATIC: 1

    steps:
      - uses: actions/checkout@v1
      - name: Musl
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get install musl musl-tools

          musl-gcc -v

      - name: Get upload url
        id: release_upload_url
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            let tag = context.payload.ref.replace(/.*\//, '');
            let release =  await github.request("GET /repos/:owner/:repo/releases/tags/:tag", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            console.log(release.data.upload_url);
            return release.data.upload_url

      - uses: actions-rs/toolchain@v1
        if: matrix.os != 'ubuntu'
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        if: matrix.os == 'ubuntu'
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Build macos
        if: matrix.os == 'macos'
        run: |
          cargo build --release --features static-openssl
          cargo build --bin gftp -p gftp --release
          cargo build --bin golem -p golem --release
          cargo build --bin ya-provider -p ya-provider --release
          cargo build --bin exe-unit -p ya-exe-unit --release --features openssl/vendored
      - name: Build windows
        if: matrix.os == 'windows'
        run: |
          vcpkg install openssl:x64-windows-static
          vcpkg integrate install

          cargo build --release
          cargo build --bin gftp -p gftp --release
          cargo build --bin golem -p golem --release
          cargo build --bin ya-provider -p ya-provider --release
          cargo build --bin exe-unit -p ya-exe-unit --release

      - name: Build linux
        if: matrix.os == 'ubuntu'
        run: |
          cargo build --release --features openssl/vendored --target x86_64-unknown-linux-musl
          cargo build --bin gftp -p gftp --release --target x86_64-unknown-linux-musl
          cargo build --bin golem -p golem --release --target x86_64-unknown-linux-musl
          cargo build --bin ya-provider -p ya-provider --release --target x86_64-unknown-linux-musl
          cargo build --bin exe-unit -p ya-exe-unit --release --features openssl/vendored --target x86_64-unknown-linux-musl
      - name: Pack
        id: pack
        shell: bash
        env:
          OS_NAME: ${{ matrix.os }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          bash .ci/pack-build.sh
      - name: Upload Release Asset [Requestor]
        id: upload-release-asset-req
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_upload_url.outputs.result }}
          asset_path: ./releases/${{ steps.pack.outputs.reqArtifact }}
          asset_name: ${{ steps.pack.outputs.reqArtifact }}
          asset_content_type: ${{ steps.pack.outputs.reqMedia }}
      - name: Upload Release Asset [Provider]
        id: upload-release-asset-prov
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_upload_url.outputs.result }}
          asset_path: ./releases/${{ steps.pack.outputs.provArtifact }}
          asset_name: ${{ steps.pack.outputs.provArtifact }}
          asset_content_type: ${{ steps.pack.outputs.provMedia }}


