name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install Clippy
      run: rustup component add clippy
      
    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
