name: Test Checker

on:
  pull_request:
    branches:
      - master
      - release/*

jobs:
  test_check:
    name: Check test results
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed ( ubuntu )
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-for-build-ubu
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Tests & Build (ubuntu-latest)"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 7200

      - name: Make sure the build was a success ( ubuntu )
        if: steps.wait-for-build-ubu.outputs.conclusion != 'success'
        run: echo job was not a success but ${{ steps.wait-for-build-ubu.outputs.conclusion }} && false

      - name: Wait for build to succeed ( windows )
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-for-build-win
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Tests & Build (windows-latest)"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 7200

      - name: Make sure the build was a success ( windows )
        if: steps.wait-for-build-win.outputs.conclusion != 'success'
        run: echo job was not a success but ${{ steps.wait-for-build-win.outputs.conclusion }} && false

      - name: Wait for build to succeed ( macos )
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-for-build-mac
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Tests & Build (macos-latest)"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 7200

      - name: Make sure the build was a success ( macos )
        if: steps.wait-for-build-mac.outputs.conclusion != 'success'
        run: echo job was not a success but ${{ steps.wait-for-build-mac.outputs.conclusion }} && false

      - name: Sleep to wait for the build to trigger
        run: sleep 1m

      - name: Wait for test to succeed
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-for-test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Integration Tests"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 1200

      - run: echo '${{ toJson(steps.wait-for-test) }}'

      - name: Fail if test was not a success
        if: steps.wait-for-test.outputs.conclusion != 'success'
        run: echo job was not a success but ${{ steps.wait-for-test.outputs.conclusion }} && false
